import Razorpay from 'razorpay';
import crypto from 'crypto';

export function getCleanRazorpayKeyId(): string | null {
  const raw = process.env.RAZORPAY_KEY_ID;
  if (!raw) return null;
  const clean = raw.replace(/^["']|["']$/g, '').trim();
  return clean.length > 0 ? clean : null;
}

export function getCleanRazorpayKeySecret(): string | null {
  const raw = process.env.RAZORPAY_KEY_SECRET;
  if (!raw) return null;
  const clean = raw.replace(/^["']|["']$/g, '').trim();
  return clean.length > 0 ? clean : null;
}

export function isRazorpayConfigured(): boolean {
  const keyId = getCleanRazorpayKeyId();
  const keySecret = getCleanRazorpayKeySecret();
  return Boolean(keyId && keySecret);
}

export function getRazorpayClient(): Razorpay | null {
  const key_id = getCleanRazorpayKeyId();
  const key_secret = getCleanRazorpayKeySecret();

  if (!key_id || !key_secret) {
    return null;
  }

  return new Razorpay({
    key_id,
    key_secret,
  });
}

/**
 * Verify HMAC SHA256 signature generated by Razorpay Checkout
 */
export function verifyRazorpaySignature(params: {
  razorpay_order_id: string;
  razorpay_payment_id: string;
  razorpay_signature: string;
}): boolean {
  const secret = getCleanRazorpayKeySecret();
  if (!secret) return false;

  const generatedSignature = crypto
    .createHmac('sha256', secret)
    .update(`${params.razorpay_order_id}|${params.razorpay_payment_id}`)
    .digest('hex');

  return generatedSignature === params.razorpay_signature;
}

/**
 * Verify Razorpay Webhook Signature
 */
export function verifyWebhookSignature(rawBody: string, signature: string): boolean {
  const rawSecret = process.env.RAZORPAY_WEBHOOK_SECRET;
  const webhookSecret = rawSecret ? rawSecret.replace(/^["']|["']$/g, '').trim() : null;
  if (!webhookSecret || !signature) return false;

  const expectedSignature = crypto
    .createHmac('sha256', webhookSecret)
    .update(rawBody)
    .digest('hex');

  return expectedSignature === signature;
}
